id: Vendr.Deploy
name: Deploy
type: Package
description: 
supportedBy: core

packageVersion: 0.2.1
docVersions:
  next: 
  current: 0.1.0
  pervious: 

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/